// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("db010c57-bdc1-4d7a-9d3e-9c6dbc00ff8f")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Probability.Tests")]
